@startuml

class FacilityManager {
    + Long: id
    * String: firstName
    * String: lastName
    * double: salary
}

class Building {
    + Long: id
    * String: typeOfBuilding
    * int: surface
}

class Room {
    + Long: id
    * boolean: used
    * int: surface
    * boolean: repairNeeded
}

class Repairing {
    + Long: id
    * String: typeOfRepair
    * String[]: toolsNeeded
    * double: fixingTime
}

FacilityManager "1" --* Building
Building "1" --* Room
Room "1" --o Repairing
FacilityManager "1" --o Repairing

@enduml